// DO NOT EDIT: Code generated by matcha from post1.matcha

import gleam/string_tree.{type StringTree}



pub fn render_tree() -> StringTree {
    let tree = string_tree.from_string("")
    let tree = string_tree.append(tree, "# This is a test post
")

    tree
}

pub fn render() -> String {
    string_tree.to_string(render_tree())
}

